#!/usr/bin/env bash
# Regenerate all shipped lock files.
#
# Run after any change to [project.dependencies] or [dependency-groups].
# CI enforces "pyproject changed => lock files regenerated" (see lock-check.yml).
#
# Outputs (all committed to version control):
#
#   uv.lock                Universal project lock generated by `uv lock`.
#                          Single source of truth — includes every group.
#                          `uv sync --group X` consults this file.
#
#   inference-cpu.lock     Flat pip-style requirements, universal, CPU torch,
#                          inference + prefect + aws groups merged.
#                          For Docker / AMI bakes that don't need CUDA.
#
#   inference-cu121.lock   Flat pip-style requirements, Linux x86_64,
#                          CUDA 12.1 torch, inference + prefect + aws.
#                          For the production GPU AMI.
#
#   dev.lock               Flat pip-style requirements, universal,
#                          superset including dev tooling.
#                          For local dev parity and CI.
set -euo pipefail

cd "$(dirname "$0")/.."

echo "==> uv.lock (universal project lock; covers every group)..."
uv lock

echo "==> inference-cpu.lock (universal, CPU torch, inference+prefect+aws)..."
uv pip compile pyproject.toml \
    --group inference --group prefect --group aws \
    --universal \
    --no-strip-extras \
    -o inference-cpu.lock

echo "==> inference-cu121.lock (Linux x86_64, CUDA 12.1, inference+prefect+aws)..."
uv pip compile pyproject.toml \
    --group inference --group prefect --group aws \
    --python-platform linux \
    --python-version 3.12 \
    --extra-index-url https://download.pytorch.org/whl/cu121 \
    --index-strategy unsafe-best-match \
    --no-strip-extras \
    -o inference-cu121.lock

echo "==> dev.lock (universal superset incl. dev tooling)..."
uv pip compile pyproject.toml \
    --group inference --group prefect --group aws --group dev \
    --universal \
    --no-strip-extras \
    -o dev.lock

echo "Done. Commit all four lock files together."
