#!/usr/bin/env bash
# Regenerate all shipped lock files.
#
# Run after any change to [project.dependencies] or [project.optional-dependencies].
# CI enforces "pyproject changed => lock files regenerated" (see lock-check.yml).
#
# Outputs (all committed to version control):
#
#   uv.lock                Universal project lock generated by `uv lock`.
#                          Single source of truth — includes every extra.
#                          `uv sync --extra X` consults this file.
#
#   lock/inference-cpu.lock     Flat pip-style requirements, universal, CPU torch,
#                               inference + prefect + aws extras merged.
#                               For Docker / AMI bakes that don't need CUDA.
#
#   lock/inference-cu121.lock   Flat pip-style requirements, Linux x86_64,
#                               CUDA 12.1 torch, inference + prefect + aws.
#                               For the production GPU AMI.
#
#   lock/dev.lock               Flat pip-style requirements, universal,
#                               superset including dev tooling.
#                               For local dev parity and CI.
set -euo pipefail

cd "$(dirname "$0")/.."
mkdir -p lock

echo "==> uv.lock (universal project lock; covers every extra)..."
uv lock

echo "==> lock/inference-cpu.lock (universal, CPU torch, inference+prefect+aws)..."
uv pip compile pyproject.toml \
    --extra inference --extra prefect --extra aws \
    --universal \
    --no-strip-extras \
    -o lock/inference-cpu.lock

echo "==> lock/inference-cu121.lock (Linux x86_64, CUDA 12.1, inference+prefect+aws)..."
# --no-sources bypasses [tool.uv.sources] CPU pin so the CUDA index wins for torch.
uv pip compile pyproject.toml \
    --extra inference --extra prefect --extra aws \
    --python-platform linux \
    --python-version 3.12 \
    --extra-index-url https://download.pytorch.org/whl/cu121 \
    --index-strategy unsafe-best-match \
    --no-sources \
    --no-strip-extras \
    -o lock/inference-cu121.lock

echo "==> lock/dev.lock (universal superset incl. dev tooling)..."
uv pip compile pyproject.toml \
    --extra inference --extra prefect --extra aws --group dev \
    --universal \
    --no-strip-extras \
    -o lock/dev.lock

echo "Done. Commit all four lock files together."
